# Generated by Django 2.2 on 2023-05-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciius',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8)),
                ('actividad', models.CharField(max_length=255)),
                ('usuario', models.CharField(max_length=100)),
            ],
        ),
    ]
