# Generated by Django 2.2 on 2023-05-14 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ciiu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciius',
            name='usuario',
        ),
    ]
